variable "sha1" {}
variable "build" {}
variable "domain_name" {}
variable "app_name" {}
variable "db_host" {}
variable "db_name" {}
variable "db_port" {}
variable "db_user" {}
variable "db_pass" {}
variable "datadog_api_key" {}
