(ns common.config)

(def STAGE (or js/process.env.STAGE "local"))
(def VERSION (or js/process.env.VERSION ""))
(def SALT (or js/process.env.SALT "$2a$04$9pk37pctRggG8IEEn8oBf.Q/UrxA07gut3e0UiH9JKHSpf2YaLbOO"))
(def API_URL (or js/process.env.API_URL "http://localhost:3000/api"))
(def SITE_BUCKET_NAME (or js/process.env.SITE_BUCKET_NAME ""))
(def GOOGLE_API_KEY (or js/process.env.NEXT_PUBLIC_GOOGLE_API_KEY ""))
(def STRIPE_SECRET_KEY (or js/process.env.STRIPE_SECRET_KEY ""))
(def RESEND_API_KEY (or js/process.env.RESEND_API_KEY ""))
