name: ci

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    name: deploy infra
    env:
      VERCEL_API_KEY: ${{ secrets.VERCEL_API_KEY }}
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6
          terraform_wrapper: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Initialize terraform
        run: |
          cd infra
          if [[ "${{github.base_ref}}" == "master" || "${{github.ref}}" == "refs/heads/master" ]]; then
            terraform init -input=false -migrate-state
            terraform workspace select prod
          fi
          if [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]; then
            terraform init -input=false -migrate-state
            terraform workspace select dev
          fi
      - name: Plan terraform
        id: plan
        run: |
          cd infra
          terraform plan -input=false -no-color -out=proposed.plan \
          && terraform show -no-color proposed.plan
      - name: Apply terraform
        if: steps.plan.outcome == 'success'
        id: apply
        run: |
          cd infra
          terraform apply \
            -input=false \
            -no-color \
            proposed.plan
