name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: team_Lg0K43FpG8zwMKKQv32wQeet
  VERCEL_PROJECT_ID: prj_0AqZ3Zu8crW1SZgp1IAxOUSZ1Hrm
on:
  push:
    branches-ignore:
      - main
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Clojurescript Artifacts
        run: cd dispatch && npm install && npm run build
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Project Artifacts to Vercel
        run: |
          pwd
          cd next
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_API_TOKEN }}
          pwd
          ls
          vercel build --token=${{ secrets.VERCEL_API_TOKEN }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_API_TOKEN }}
