name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: team_Lg0K43FpG8zwMKKQv32wQeet
  VERCEL_PROJECT_ID: prj_0AqZ3Zu8crW1SZgp1IAxOUSZ1Hrm
on:
  push:
    branches-ignore:
      - master
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
      - name: Build Clojurescript
        run: |
          cd cljs
          bun install
          bun run build
      - name: Build & Deploy Next
        run: |
          bun install --global vercel@latest
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_API_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_API_TOKEN }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_API_TOKEN }}
