name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: team_Lg0K43FpG8zwMKKQv32wQeet
  VERCEL_PROJECT_ID: prj_0AqZ3Zu8crW1SZgp1IAxOUSZ1Hrm
on:
  push:
    branches:
      - master
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
      - name: Setup Environment
        run: |
          bun install --global vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_API_TOKEN }}
      - name: Build Clojurescript
        run: |
          . ./.vercel/.env.production.local
          cd cljs
          bunx prisma generate
          bun install
          bun run build
      - name: Build & Deploy
        run: |
          bunx prisma generate --schema=./cljs/prisma/schema.prisma
          vercel build --prod --token=${{ secrets.VERCEL_API_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_API_TOKEN }}
