name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: team_Lg0K43FpG8zwMKKQv32wQeet
  VERCEL_PROJECT_ID: prj_0AqZ3Zu8crW1SZgp1IAxOUSZ1Hrm
on:
  push:
    branches:
      - master
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Environment
        run: |
          pnpm install --global vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_API_TOKEN }}
          pnpm install
          pnpm dlx prisma generate
      - name: Build Clojurescript
        run: |
          . ./.vercel/.env.production.local
          pnpm shadow:build
      - name: Build & Deploy
        run: |
          vercel build --prod --token=${{ secrets.VERCEL_API_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_API_TOKEN }}
